ProperSalads/Areas/SaladsOfAdmin/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using ProperSalads.DAL;
using ProperSalads.Models;
using System;

namespace ProperSalads.Areas.SaladsOfAdmin.Controllers
{
    [Area("SaladsOfAdmin")]
    public class SettingsController : Controller
    {
        readonly SaladPageDbContext _context;
        public SettingsController(SaladPageDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Setting> settings = _context.Settings.AsEnumerable();
            return View(settings);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Setting newSettings)
        {
            if (newSettings.Key is null || newSettings.Value is null)
            {
                ModelState.AddModelError("", "Please enter Key and Value");
                return View();
            }
            _context.Settings.Add(newSettings);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            if (id == 0) return BadRequest();
            Setting? setting = _context.Settings.FirstOrDefault(s => s.Id == id);
            if (setting == null) return BadRequest();
            return View(setting);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Setting newSetting)
        {
            if (id != newSetting.Id) return BadRequest();
            Setting? oldSetting = _context.Settings.FirstOrDefault(s => s.Id == id);
            if (!ModelState.IsValid) return BadRequest();
            oldSetting.Key = newSetting.Key;
            oldSetting.Value = newSetting.Value;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Setting? setting = _context.Settings.FirstOrDefault(s => s.Id == id);
            return View(setting);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Setting deleted)
        {

            _context.Settings.Remove(deleted);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detail(int id)
        {
            Setting? setting = _context.Settings.FirstOrDefault(s => s.Id == id);
            return View(setting);
        }
    }
}

ProperSalads/Controllers/FruitSaladController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using ProperSalads.DAL;
using ProperSalads.Models;
using System.Diagnostics;

namespace ProperSalads.Controllers
{
    public class FruitSaladController : Controller
    {
        private readonly SaladPageDbContext _context;

        public FruitSaladController(SaladPageDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Products = _context.FruitSalads
                                      .Include(fs => fs.GetFruitsaladImages)?
                                      .Include(fs => fs.SaladAndFruits)
                                      .ThenInclude(saf => saf.Fruit)
                                      .ThenInclude(f => f.fruitCategories).OrderByDescending(fs => fs.Id).Take(4).ToList();
            return View();
        }

        public IActionResult Detail(int id)
        {
            ViewBag.Products = _context.FruitSalads
                                    .Include(fs => fs.GetFruitsaladImages)?
                                    .Include(fs => fs.SaladAndFruits)
                                    .ThenInclude(saf => saf.Fruit)
                                    .ThenInclude(f => f.fruitCategories).OrderByDescending(fs => fs.Id).Take(4).ToList();

            ViewBag.AllFruits = _context.Fruits.ToList();
            if (id == 0) return NotFound();

            FruitSalad? fruitSalad = _context.FruitSalads.FirstOrDefault(fs => fs.Id == id);

            if (fruitSalad is null) return NotFound();
            return View(fruitSalad);
        }
    }
}

ProperSalads/Views/Shared/_FruitSaladPartial.cshtml
@model List<FruitSalad>
@{
    string[] a = { "asdasd", "asdasda", "asdasaf", "asdasag" };
}
@foreach(var item in Model){
    <div class="col-lg-3 col-md-6">
        <div class="image-info">
            <div class="image-icon">
                <div class="image">
                    <img src="~/assets/images/@item.GetFruitsaladImages?.Path" alt="Product">
                </div>
                <div class="heartIcon">
                    <i class="bi bi-heart"></i>
                </div>
            </div>
            <div class="info">
                <div class="rating">
                    <div class="star-icon">
                        <i class="bi bi-star"></i>
                    </div>
                    <div class="point">
                        <p>4.7</p>
                    </div>
                </div>

                <div class="name-comp">
                    <h3 style ="font-size:22px"><a asp-controller="FruitSalad" asp-action="Detail" asp-route-id="@item.Id">@(item.Name.Length > 14 ? item.Name.Substring(0,14) + "..." : item.Name)</a></h3>
                   <p>
                        @foreach (var fruit in item.SaladAndFruits.Take(2))
                        {
                            @(fruit.Fruit.Name)

                            @(fruit != item.SaladAndFruits.Skip(1).FirstOrDefault() ? ", " : "")
                        }
                        @if (item.SaladAndFruits.Count > 2)
                        {
                            <text> ...</text>
                        }
                    </p>
                </div>
                <div class="dollar-price">
                    $<span class="price">@item.Price</span>
                </div>
            </div>
        </div>
    </div>
}

ProperSalads/Views/Shared/_Layout.cshtml
@using ProperSalads.Services;
@inject LayoutService layoutService
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/assets/css/header-footer.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/shop.css">
    <link rel="stylesheet" href="~/assets/css/basket.css>
    <link rel="stylesheet" href="~/assets/css/create.css">
    <link rel="stylesheet" href="~/assets/css/detail.css">
    <link rel="stylesheet" href="~/assets/css/menu.css">
    <link rel="stylesheet" href="~/assets/css/.css">
    <title>Home Page</title>
</head>

<body>
    <header>
        <div class="container">
            <div class="row headerUp ">
                <div class="col-lg-3 col-6">
                    <div class="logo">
                        <a href="">
                            <img src="~/assets/images/@layoutService.GetSettings().FirstOrDefault(l => l.Key == "Logo")?.Value" alt="ProperLogo">
                        </a>
                    </div>
                </div>
                <div class="col-lg-5 d-lg-block d-none mt-2">
                    <div class="menu">
                        <ul class="ulMenu">
                            <li><a asp-controller="FruitSalad" asp-action="Index">Fruit mix</a></li>
                            <li><a href="./create.html">Customize</a></li>
                            <li><a href="">Contact us</a></li>
                            <li><a href="">About us</a></li>
                            <li><a asp-area="SaladsOfAdmin" asp-controller="Settings" asp-action="Index">Admin Panel</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-6 d-lg-block d-none mt-2">
                    <div class="menu">
                        <ul class="ulMenuIcons">
                            <li class="basket-icon">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "basketIcon")?.Value)
                            </li>
                            <li>
                                <a href="">
                                    @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "wishlistIcon")?.Value)
                                </a>
                            </li>
                            <li class="search-icon">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "searchIcon")?.Value)
                            </li>
                            <ul class="search-input">
                                <li>
                                    <input type="text" name="" id="" placeholder="Search...">
                                </li>
                            </ul>
                            <li class="person-icon">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "personIcon")?.Value)
                            </li>
                            <ul class="person-info">
                                <li>
                                    <p><a href="">Sign up</a></p>
                                    <p><a href="">Sign in</a></p>
                                </li>
                            </ul>
                        </ul>
                    </div>
                </div>
                <div class="col-6">
                    <div class="hamburgerIcon ">
                        <ul class="ulMenuIcons">
                            <li class="search-icon">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "searchIcon")?.Value)
                            </li>
                            <ul class="search-input">
                                <li>
                                    <input type="text" name="" id="" placeholder="Search...">
                                </li>
                            </ul>
                            <li class="basket-icon">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "basketIcon")?.Value)
                            </li>
                            <li class="hamburger-icon">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(l => l.Key == "hamburgerIcon")?.Value)
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="side-menu">
                    <div class="menu-title">
                        <p class="X-btn">
                            <i class="bi bi-x-lg"></i>
                        </p>
                    </div>
                    <div class="menu-infos">
                        <ul class="menu-hover">
                            <li><a href="#">Fruit mix</a></li>
                            <li><a href="#">Customize</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li class="account-li"><a href="#">Account <i class="bi bi-chevron-down"></i></a></li>
                            <ul class="account-acordion">
                                <li><a href="#">Sgin up</a></li>
                                <li><a href="#">Sign in</a></li>
                            </ul>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">About us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="side-basket">
                    <div class="menu-title">
                        <p class="X-btn">
                            <i class="bi bi-x-lg"></i>
                        </p>
                    </div>
                    <div class="products-image-infos">
                        <div class="row">
                            <div class="image col-4">
                                <img width="100%" src="~/assets/images/uzumbanan.png" alt="">
                            </div>
                            <div class="infos col-8">
                                <h6>Name: <span>Uzumbanan</span></h6>
                                <p>Categories <span>Soft</span></p>
                                <p>Quantity: 1</p>
                                <p>Price: $18</p>

                            </div>
                        </div>
                    </div>
                    <div class="products-image-infos">
                        <div class="row">
                            <div class="image col-4">
                                <img width="100%" src="~/assets/images/uzumbanan.png" alt="">
                            </div>
                            <div class="infos col-8">
                                <h6>Name: <span>Uzumbanan</span></h6>
                                <p>Categories <span>Soft</span></p>
                                <p>Quantity: 1</p>
                                <p>Price: $18</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    <footer>
        <div class="container">
            <div class="row all-footer-info">
                <div class="col-lg-9 col-6">
                    <div class="footerLogo">
                        <img src="~/assets/images/@layoutService.GetSettings().FirstOrDefault(l => l.Key == "Logo")?.Value" alt="">
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="applications">
                        <div class="app" style="width: 160px; height: 46px;">
                            <a href="">
                                <img style="width: 100%;" src="~/assets/images/playStore.png" alt="">
                            </a>
                        </div>
                        <div class="app" style="width: 160px; height: 46px;">
                            <a href="">
                                <img style="width: 100%;" src="~/assets/images/appStore.png" alt="">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="free-line"></div>

                <div class="col-lg-3 col-12 reserved">
                    <p>2022-2024</p>
                    <p>All rights reserved.</p>
                </div>
                <div class="col-lg-2 col-6 footerInfos">
                    <h4>Customize</h4>
                    <ul>
                        <li><a href="">About Us</a></li>
                        <li><a href="">Fruit Club</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-6 footerInfos">
                    <h4>Corporate</h4>
                    <ul>
                        <li><a href="">Privacy policy</a></li>
                        <li><a href="">Terms & Conditions</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-6 footerInfos">
                    <h4>Growing Fruits</h4>
                    <ul>
                        <li> <a href="">FAQ</a></li>
                        <li><a href="">Special offers</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-6 contact">
                    <h4>Contact</h4>
                    <ul>
                        <li>
                            <a href="" style="color: #2EDC87;">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(ls => ls.Key == "contactFacebook")?.Value)
                            </a>
                        </li>
                        <li>
                            <a href="" style="color: #2EDC87;">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(ls => ls.Key == "contactInstagram")?.Value)
                            </a>
                        </li>
                        <li>
                            <a href="" style="color: #2EDC87;">
                                @Html.Raw(layoutService.GetSettings().FirstOrDefault(ls => ls.Key == "contactTwitter")?.Value)
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


    <script>
        AOS.init({
            delay: 100,
            duration: 800,
            easing: 'ease-in-in',
            once: true
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
            integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/assets/js/header-footer.js"></script>
    <script src="~/assets/js/shop.js"></script>
    <script src="~/assets/js/NotFound.js"></script>

</body>

</html>